# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
  - stage: Build
    jobs:
      - job: buildwebapp
        pool: 
          vmImage: 'ubuntu-latest'

        steps:
        - script: echo Hello, world!
          displayName: 'Run a one-line script'
        
        - task: UseDotNet@2
          inputs:
            packageType: 'runtime'
            version: '5.8'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'publish'
            publishWebProjects: true
            arguments: '--configuration $(buildConfiguration) --output $(Build.BinariesDirectory)/$(Build.BuildId)'
            workingDirectory: 'src'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.BinariesDirectory)/$(Build.BuildId)'
            ArtifactName: 'drop-$(Build.BuildId)'
            publishLocation: 'Container'